apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: v1
    app: players
  name: players
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: players
  template:
    metadata:
      labels:
        app: players
        version: v1
        stack: echo
        interface: rest
        language: golang
    spec:
      containers:
        - image: ramonpacheco/players:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "20Mi"
              cpu: "150m"
            limits:
              memory: "30Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 9999
              scheme: HTTP
            initialDelaySeconds: 1
          name: players
          ports:
            - containerPort: 9999
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 9999
              scheme: HTTP
            initialDelaySeconds: 1
